version: "3.9"
services:

  configserver:
    build: .
    ports:
      - "8888:8888"
    healthcheck:
      test: "curl --fail --silent localhost:8888/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s

  configclient1:
    build: ../customers-stores/rest-microservices-store
    depends_on:
      configserver:
        condition: service_healthy
    links:
      - "configserver"
    ports:
      - "8081:8081"

  configclient2:
    build: ../customers-stores/rest-microservices-store
    depends_on:
      configserver:
        condition: service_healthy
    links:
      - "configserver"
    ports:
      - "8082:8081"



