version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  configserver:
    build: .
    links:
      - "rabbitmq"
    ports:
      - "8888:8888"

  configclient1:
    build: ../spring-cloud-config-client
    links:
      - "rabbitmq"
      - "configserver"
    ports:
      - "8081:8081"

  configclient2:
    build: ../spring-cloud-config-client
    links:
      - "rabbitmq"
      - "configserver"
    ports:
      - "8082:8081"



