server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - bus-refresh
  endpoint:
    env:
      post:
        enabled: true
logging:
  level:
    org.springframework.cloud: 'DEBUG'

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/aditya-mittal/config-repo
          basedir: target/config
          default-label: main
    bus:
      enabled: false